- name: "鈴木龍平"
  image: "profile-saki.jpg"
  bio: "生年月日：1996/01/31"
  twitter_url: "https://twitter.com/Ryu_su_131"
  instagram_url: "https://www.instagram.com/intk__7"

- name: "まえかず"
  image: "profile-maekz.jpg"
  bio: "生年月日：1994/12/22"
  twitter_url: "https://twitter.com/intmaekz"
  instagram_url: "https://www.instagram.com/int_maekz"
